name: CI Pipeline AS1

on:
    push:

jobs:
    test-build:
        runs-on: ubuntu-latest
        steps:
        
          - name: assignment1
            uses: actions/checkout@v6
       
          - name: setup python
            uses: actions/setup-python@v5
            with: python-version: '3.12'

          - name: install dependencies
            run: |
                cd Assignment1
                pip install -r requirements.txt

          - name: run tests
            run: |
                cd Assignment1
                pytest
