name: CD Pipeline

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Deploy to EC2 via SSH
              uses: appleboy/ssh-action@v.1.0.3
              with:
                host: ${{secrets.EC2_HOST}}
                username: ${{secrets.EC2_USERNAME}}
                key: ${{secrets.EC2_SSH_KEY}}
                script: |
                    aws ecr get-login-password --region ${{vars.AWS_REGION}} | docker login --username AWS --password-stdin ${{vars .AWS_ACCOUNT_ID }}.dkr.ecr.${{vars.AWS_REGION}}.amazonaws.com
                    docker pull ${{vars.ECR_REPOSITORY}}:${{vars.IMAGE_TAG}}
                    docker stop ${{vars.CONTAINER_NAME}} || true
                    docker rm ${{vars.CONTAINER_NAME}} || true
                    docker run -d --name ${{vars.CONTAINER_NAME}} -p ${{vars.HOST_PORT}}:${{vars.CONTAINERS_PORT}} ${{vars.ECR_REPOSITORY}}:${{vars.IMAGE_TAG}}
