name: Coderco Secrets CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: checkout code
          uses: actions/checkout@v4

        - name: use secret
          run: echo "The secret is ${{secrets.MY_SECRET}}"
